CREATE TABLE [dbo].[f_events] (
    [id_exc]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [id_event]                     NVARCHAR (50)   NOT NULL,
    [culture]                      CHAR (5)        NULL,
    [id_type_event]                INT             NULL,
    [id_status_event]              INT             NULL,
    [id_affiliate]                 INT             NULL,
    [id_channel]                   INT             NULL,
    [id_group]                     INT             NULL,
    [id_customer]                  INT             NULL,
    [id_product]                   INT             NULL,
    [id_supplier]                  INT             NULL,
    [id_currency]                  INT             NULL,
    [id_promotion]                 INT             NULL,
    [id_department]                INT             NULL,
    [id_organization]              INT             NULL,
    [id_structure]                 INT             NULL,
    [id_geography]                 INT             NULL,
    [id_territory]                 INT             NULL,
    [id_histo]                     INT             NULL,
    [id_version_event]             INT             NULL,
    [detail1]                      NVARCHAR (MAX)  NULL,
    [detail2]                      NVARCHAR (MAX)  NULL,
    [quantity]                     INT             NULL,
    [unit_price_ex_vat]            DECIMAL (18, 4) NULL,
    [unit_price_vat]               DECIMAL (18, 4) NULL,
    [production_cost]              DECIMAL (18, 4) NULL,
    [percentage_vat]               DECIMAL (18, 4) NULL,
    [discount_percentage]          DECIMAL (18, 4) NULL,
    [percentage_margin]            DECIMAL (18, 4) NULL,
    [total_event_margin]           DECIMAL (18, 4) NULL,
    [discount_amount]              DECIMAL (18, 4) NULL,
    [total_event_amount]           DECIMAL (18, 4) NULL,
    [date_event]                   DATE            NULL,
    [date_delivery_event]          DATETIME        NULL,
    [date_facturation_event]       DATETIME        NULL,
    [date_billing_event]           DATETIME        NULL,
    [date_payment_event]           DATETIME        NULL,
    [date_record_event]            DATETIME        NULL,
    [date_import]                  DATETIME        NULL,
    [id_payee]                     INT             NULL,
    [id_category_payee]            INT             NULL,
    [id_grade_payee]               INT             NULL,
    [id_contract_payee]            INT             NULL,
    [id_agreement_payee]           INT             NULL,
    [id_cost_center_payee]         INT             NULL,
    [id_gender_payee]              INT             NULL,
    [id_activity_status_payee]     INT             NULL,
    [id_job_payee]                 INT             NULL,
    [id_department_payee]          INT             NULL,
    [id_organization_payee]        INT             NULL,
    [id_structure_1_payee]         INT             NULL,
    [id_structure_2_payee]         INT             NULL,
    [id_geography_payee]           INT             NULL,
    [id_territory_payee]           INT             NULL,
    [id_variable_currency_payee]   INT             NULL,
    [id_title_payee]               INT             NULL,
    [id_nationality_payee]         INT             NULL,
    [id_pool_payee]                INT             NULL,
    [id_job_country_payee]         INT             NULL,
    [id_benefit_payee]             INT             NULL,
    [id_salary_currency_payee]     INT             NULL,
    [id_payment_currency_payee]    INT             NULL,
    [id_band_payee]                INT             NULL,
    [id_businessunit_payee]        INT             NULL,
    [id_division_payee]            INT             NULL,
    [id_host_country_payee]        INT             NULL,
    [id_home_country_payee]        INT             NULL,
    [id_jobfamily_payee]           INT             NULL,
    [activation_fee]               DECIMAL (18, 4) NULL,
    [monthly_recurring_fee]        DECIMAL (18, 4) NULL,
    [total_contract_value]         DECIMAL (18, 4) NULL,
    [small_subscription_quantity]  DECIMAL (18, 4) NULL,
    [medium_subscription_quantity] DECIMAL (18, 4) NULL,
    [large_subscription_quantity]  DECIMAL (18, 4) NULL,
    [id_manufacturer]              DECIMAL (18, 4) NULL,
    [id_licencing_type]            INT             NULL,
    [id_business_unit]             INT             NULL,
    [id_division]                  INT             NULL,
    CONSTRAINT [PK_f_events] PRIMARY KEY CLUSTERED ([id_exc] ASC),
    CONSTRAINT [FK_f_events_Dim_Channel] FOREIGN KEY ([id_channel]) REFERENCES [dbo].[Dim_Channel] ([id_channel]),
    CONSTRAINT [FK_f_events_Dim_Currency] FOREIGN KEY ([id_currency]) REFERENCES [dbo].[Dim_Currency] ([id_currency]),
    CONSTRAINT [FK_f_events_Dim_Customer] FOREIGN KEY ([id_customer]) REFERENCES [dbo].[Dim_Customer] ([id_customer]),
    CONSTRAINT [FK_f_events_Dim_Department] FOREIGN KEY ([id_department]) REFERENCES [dbo].[Dim_Department_bqm] ([id_department]),
    CONSTRAINT [FK_f_events_Dim_Geography] FOREIGN KEY ([id_geography]) REFERENCES [dbo].[Dim_Geography] ([id_geography]),
    CONSTRAINT [FK_f_events_Dim_Group] FOREIGN KEY ([id_group]) REFERENCES [dbo].[Dim_Group] ([id_group]),
    CONSTRAINT [FK_f_events_Dim_Organization] FOREIGN KEY ([id_organization]) REFERENCES [dbo].[Dim_Organization] ([id_organization]),
    CONSTRAINT [FK_f_events_Dim_Product] FOREIGN KEY ([id_product]) REFERENCES [dbo].[Dim_Product] ([id_product]),
    CONSTRAINT [FK_f_events_Dim_Promotion] FOREIGN KEY ([id_promotion]) REFERENCES [dbo].[Dim_Promotion] ([id_promotion]),
    CONSTRAINT [FK_f_events_Dim_Status] FOREIGN KEY ([id_status_event]) REFERENCES [dbo].[Dim_Status] ([id_status]),
    CONSTRAINT [FK_f_events_Dim_Structure] FOREIGN KEY ([id_structure]) REFERENCES [dbo].[Dim_Structure] ([id_structure]),
    CONSTRAINT [FK_f_events_Dim_Supplier] FOREIGN KEY ([id_supplier]) REFERENCES [dbo].[Dim_Supplier] ([id_supplier]),
    CONSTRAINT [FK_f_events_Dim_Territory] FOREIGN KEY ([id_territory]) REFERENCES [dbo].[Dim_Territory] ([id_territory]),
    CONSTRAINT [FK_f_events_Dim_Type_Event] FOREIGN KEY ([id_type_event]) REFERENCES [dbo].[Dim_Type_Event] ([id_type_event]),
    CONSTRAINT [FK_f_events_Dim_Version_Event] FOREIGN KEY ([id_version_event]) REFERENCES [dbo].[Dim_Version_Event] ([id_version_event]),
    CONSTRAINT [FK_f_events_k_collaborateurs_histo] FOREIGN KEY ([id_histo]) REFERENCES [dbo].[py_PayeeHisto] ([id_histo])
);


GO
CREATE NONCLUSTERED INDEX [IX_f_events]
    ON [dbo].[f_events]([id_histo] ASC, [id_type_event] ASC, [id_status_event] ASC, [id_product] ASC, [id_structure] ASC, [id_organization] ASC, [id_department] ASC, [id_geography] ASC, [id_territory] ASC, [id_affiliate] ASC, [id_channel] ASC, [id_customer] ASC, [id_supplier] ASC, [id_currency] ASC, [id_promotion] ASC, [id_group] ASC);

