CREATE TABLE [dbo].[k_m_plans_field_validation] (
    [id_plans_field_validation]         INT            IDENTITY (1, 1) NOT NULL,
    [id_plan]                           INT            NOT NULL,
    [id_indicator_field]                INT            NULL,
    [id_planInfo]                       INT            NULL,
    [formula]                           NVARCHAR (MAX) NOT NULL,
    [action_false_allow_saving]         BIT            CONSTRAINT [DF_k_m_plans_field_validation_action_false_allow_saving] DEFAULT ((0)) NOT NULL,
    [action_false_show_error]           BIT            CONSTRAINT [DF_k_m_plans_field_validation_action_false_show_error] DEFAULT ((1)) NOT NULL,
    [action_false_error_message]        NVARCHAR (MAX) NULL,
    [action_false_use_field_style]      BIT            CONSTRAINT [DF_k_m_plans_field_validation_action_false_use_field_style] DEFAULT ((0)) NOT NULL,
    [action_false_text_color]           NVARCHAR (50)  NOT NULL,
    [action_false_border_color]         NVARCHAR (50)  NOT NULL,
    [action_false_background_color]     NVARCHAR (50)  NOT NULL,
    [action_true_use_field_style]       BIT            CONSTRAINT [DF_k_m_plans_field_validation_action_true_use_field_style] DEFAULT ((0)) NOT NULL,
    [action_true_text_color]            NVARCHAR (50)  NOT NULL,
    [action_true_border_color]          NVARCHAR (50)  NOT NULL,
    [action_true_background_color]      NVARCHAR (50)  NOT NULL,
    [id_plan_indicator]                 INT            NULL,
    [action_false_show_error_on_change] BIT            NOT NULL,
    [enable_client_side_validation]     BIT            DEFAULT ((1)) NOT NULL,
    [action_false_allow_editing]        BIT            NOT NULL,
    CONSTRAINT [PK_k_m_plans_field_validation] PRIMARY KEY CLUSTERED ([id_plans_field_validation] ASC),
    CONSTRAINT [CK_between_idField_and_idIndicatorField] CHECK (NOT ([id_indicator_field] IS NOT NULL AND [id_planInfo] IS NOT NULL)),
    CONSTRAINT [FK_indicatorsFields_plansFieldValidation] FOREIGN KEY ([id_indicator_field]) REFERENCES [dbo].[k_m_indicators_fields] ([id_indicator_field]),
    CONSTRAINT [FK_k_m_plans_field_validation_TO_k_m_plans_indicators] FOREIGN KEY ([id_plan_indicator]) REFERENCES [dbo].[k_m_plans_indicators] ([id_plan_indicator]),
    CONSTRAINT [FK_k_plans_information_with_id_field] FOREIGN KEY ([id_plans_field_validation]) REFERENCES [dbo].[k_m_plans_field_validation] ([id_plans_field_validation]),
    CONSTRAINT [FK_plansFieldValidation_kmplans] FOREIGN KEY ([id_plan]) REFERENCES [dbo].[k_m_plans] ([id_plan]),
    CONSTRAINT [FK_plansInformation_planFieldValidation] FOREIGN KEY ([id_planInfo]) REFERENCES [dbo].[k_m_plans_informations] ([id_planInfo])
);

