CREATE TABLE [dbo].[k_m_plan_form_content] (
    [plan_form_field_id]       INT            IDENTITY (1, 1) NOT NULL,
    [parent_form_container_id] INT            NOT NULL,
    [field_id]                 INT            NULL,
    [planInfo_id]              INT            NULL,
    [plan_id]                  INT            NOT NULL,
    [indicator_id]             INT            NULL,
    [multiline_allowed]        BIT            CONSTRAINT [DF_k_m_plan_form_content_multiline_allowed] DEFAULT ((0)) NOT NULL,
    [row_span]                 INT            CONSTRAINT [DF_k_m_plan_form_content_row_span] DEFAULT ((1)) NOT NULL,
    [width]                    INT            CONSTRAINT [DF_k_m_plan_form_content_width] DEFAULT ((250)) NOT NULL,
    [show_label]               BIT            CONSTRAINT [DF_k_m_plan_form_content_show_label] DEFAULT ((1)) NOT NULL,
    [text_width]               INT            CONSTRAINT [DF_k_m_plan_form_content_text_width] DEFAULT ((100)) NOT NULL,
    [id_source_tenant]         INT            NULL,
    [id_source]                INT            NULL,
    [id_change_set]            INT            NULL,
    [field_type]               INT            DEFAULT ((1)) NULL,
    [label_text]               NVARCHAR (MAX) NULL,
    [use_html_editor]          BIT            DEFAULT ((0)) NULL,
    [show_indicator_name]      BIT            DEFAULT ((0)) NULL,
    [indicator_control_type]   INT            NULL,
    [fields_per_row]           INT            NULL,
    [use_translate]            BIT            CONSTRAINT [DF_k_m_plan_form_content_use_translate] DEFAULT ((0)) NOT NULL,
    [description]              NVARCHAR (MAX) NULL,
    [visibility_condition]     NVARCHAR (MAX) NULL,
    [currency_information]     INT            NULL,
    CONSTRAINT [PK_k_m_plan_form_field] PRIMARY KEY CLUSTERED ([plan_form_field_id] ASC),
    CONSTRAINT [FK_k_m_plan_form_content_k_m_indicators] FOREIGN KEY ([indicator_id]) REFERENCES [dbo].[k_m_indicators] ([id_ind]),
    CONSTRAINT [FK_k_m_plan_form_content_k_m_plans] FOREIGN KEY ([plan_id]) REFERENCES [dbo].[k_m_plans] ([id_plan]),
    CONSTRAINT [FK_k_m_plan_form_content_k_m_plans_informations] FOREIGN KEY ([planInfo_id]) REFERENCES [dbo].[k_m_plans_informations] ([id_planInfo]),
    CONSTRAINT [FK_k_m_plan_form_field_k_m_fields] FOREIGN KEY ([field_id]) REFERENCES [dbo].[k_m_fields] ([id_field]),
    CONSTRAINT [FK_k_m_plan_form_field_k_m_plan_form_field] FOREIGN KEY ([parent_form_container_id]) REFERENCES [dbo].[k_referential_form_container] ([container_id])
);

