CREATE TABLE [dbo].[k_m_fields] (
    [id_field]                    INT            IDENTITY (1, 1) NOT NULL,
    [name_field]                  NVARCHAR (100) NOT NULL,
    [label_field]                 NVARCHAR (255) NOT NULL,
    [code_field]                  NVARCHAR (255) NOT NULL,
    [width]                       INT            NULL,
    [id_unit]                     INT            NOT NULL,
    [id_field_type]               INT            NOT NULL,
    [id_control_type]             INT            NOT NULL,
    [type_value]                  NVARCHAR (50)  NOT NULL,
    [default_type]                NVARCHAR (50)  NULL,
    [default_value]               NVARCHAR (255) NULL,
    [min_type]                    NVARCHAR (50)  NULL,
    [min_value]                   NVARCHAR (255) NULL,
    [max_type]                    NVARCHAR (50)  NULL,
    [max_value]                   NVARCHAR (255) NULL,
    [percentage_type]             NVARCHAR (50)  NULL,
    [percentage_value]            NVARCHAR (255) NULL,
    [percentage_mode]             NVARCHAR (50)  NULL,
    [is_olap]                     BIT            CONSTRAINT [DF_k_m_fields_is_olap] DEFAULT ((0)) NOT NULL,
    [olap_aggregate_function]     NVARCHAR (255) NULL,
    [id_user_create]              INT            NULL,
    [date_create_field]           DATETIME       CONSTRAINT [DF_k_m_fields_date_create_field] DEFAULT (getdate()) NULL,
    [id_user_update]              INT            NULL,
    [date_update_field]           DATETIME       NULL,
    [show_min]                    BIT            CONSTRAINT [DF_k_m_fields_show_min] DEFAULT ((1)) NOT NULL,
    [show_max]                    BIT            CONSTRAINT [DF_k_m_fields_show_max] DEFAULT ((1)) NOT NULL,
    [formula]                     NVARCHAR (255) NULL,
    [thousand_separator]          BIT            NULL,
    [decimal_precision]           INT            NULL,
    [id_source_tenant]            INT            NULL,
    [id_source]                   INT            NULL,
    [id_change_set]               INT            NULL,
    [id_reference_measure]        INT            NULL,
    [id_access_type]              INT            CONSTRAINT [DF_k_m_fields_id_access_type] DEFAULT ((-1)) NOT NULL,
    [is_percentage_used]          BIT            CONSTRAINT [DF_k_m_fields_is_percentage_used] DEFAULT ((0)) NOT NULL,
    [value_filter]                NVARCHAR (20)  CONSTRAINT [DF_k_m_fields_value_filter] DEFAULT ((1)) NULL,
    [show_aggregated_result]      BIT            DEFAULT ((0)) NOT NULL,
    [threshold_comparison_field]  INT            NULL,
    [threshold_min_value]         TINYINT        NULL,
    [threshold_max_value]         TINYINT        NULL,
    [is_threshold_enabled]        BIT            NULL,
    [show_only_aggregated_result] BIT            DEFAULT ((0)) NOT NULL,
    [aggregation_type]            INT            CONSTRAINT [DF_k_m_fields_aggregation_type] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_k_m_fields] PRIMARY KEY CLUSTERED ([id_field] ASC),
    CONSTRAINT [FK_k_m_fields_k_m_field_access_type] FOREIGN KEY ([id_access_type]) REFERENCES [dbo].[k_m_field_access_type] ([id_access_type]),
    CONSTRAINT [FK_k_m_fields_k_m_olap_references] FOREIGN KEY ([id_reference_measure]) REFERENCES [dbo].[k_m_olap_references] ([id_reference])
);

