CREATE TABLE [dbo].[k_program_cond] (
    [id_prog]             INT            NULL,
    [id_cond]             INT            IDENTITY (1, 1) NOT NULL,
    [name_cond]           NVARCHAR (50)  NOT NULL,
    [html_calc]           NVARCHAR (MAX) NULL,
    [sql_calc]            NVARCHAR (MAX) NULL,
    [html_cond]           NVARCHAR (MAX) NULL,
    [sql_cond]            NVARCHAR (MAX) NULL,
    [active_cond]         BIT            CONSTRAINT [DF_k_program_cond_active_cond] DEFAULT ((0)) NOT NULL,
    [id_universe]         INT            NOT NULL,
    [mode_cond]           NVARCHAR (50)  NOT NULL,
    [date_last_calc_cond] DATETIME       NULL,
    [date_begin_cond]     SMALLDATETIME  NULL,
    [date_end_cond]       SMALLDATETIME  NULL,
    [id_group1]           INT            NULL,
    [id_group2]           INT            NULL,
    [id_group3]           INT            NULL,
    [id_group4]           INT            NULL,
    [id_group5]           INT            NULL,
    [comments_cond]       NVARCHAR (MAX) NULL,
    [id_owner]            INT            NULL,
    [date_created]        SMALLDATETIME  NULL,
    [date_last_modified]  SMALLDATETIME  NULL,
    [filter_current_user] NVARCHAR (50)  NULL,
    [html_additionalCond] NVARCHAR (MAX) NULL,
    [sql_additionalCond]  NVARCHAR (MAX) NULL,
    [param_merge_type]    VARCHAR (8)    CONSTRAINT [DF_k_program_cond_param_merge_type] DEFAULT ('none') NOT NULL,
    [sql_deleteCond]      NVARCHAR (MAX) NULL,
    [id_source_tenant]    INT            NULL,
    [id_source]           INT            NULL,
    [id_change_set]       INT            NULL,
    [smart_mode_used]     BIT            CONSTRAINT [DF_k_program_cond_smart_mode_used] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_k_program_cond] PRIMARY KEY CLUSTERED ([id_cond] ASC),
    CONSTRAINT [FK_k_program_cond_k_program] FOREIGN KEY ([id_prog]) REFERENCES [dbo].[k_program] ([id_prog]) ON DELETE CASCADE,
    CONSTRAINT [FK_k_program_cond_k_program_cond_universes] FOREIGN KEY ([id_universe]) REFERENCES [dbo].[k_program_cond_universes] ([id_universe])
);

