CREATE TABLE [dbo].[k_referential_form_field] (
    [field_id]                    INT            IDENTITY (1, 1) NOT NULL,
    [form_id]                     INT            NOT NULL,
    [field_text]                  NVARCHAR (255) NOT NULL,
    [table_view_field_id]         INT            NULL,
    [id_customTableView]          INT            NULL,
    [comments]                    NVARCHAR (MAX) NULL,
    [control_order]               INT            NOT NULL,
    [control_type]                INT            NOT NULL,
    [is_foreign]                  BIT            NOT NULL,
    [control_width]               INT            NOT NULL,
    [control_height]              INT            NOT NULL,
    [column_span]                 INT            NOT NULL,
    [regular_expression]          NVARCHAR (100) NULL,
    [is_key]                      BIT            NOT NULL,
    [is_editable]                 BIT            NOT NULL,
    [foreign_table_id]            INT            NULL,
    [foreign_key_field_id]        INT            NULL,
    [foreign_text_field_id]       INT            NULL,
    [foreign_order_field_id]      INT            NULL,
    [foreign_culture_field_name]  NVARCHAR (100) NULL,
    [default_value]               NVARCHAR (MAX) NULL,
    [grid_filter_field]           NVARCHAR (50)  NULL,
    [parent_key_field_id]         INT            NULL,
    [unit_id]                     INT            NULL,
    [form_template_item_name]     NVARCHAR (50)  NULL,
    [parent_field_id]             INT            NULL,
    [parent_form_container_id]    INT            NULL,
    [text_width]                  INT            NULL,
    [thousand_separator]          BIT            NULL,
    [decimal_precision]           INT            NULL,
    [id_source_tenant]            INT            NULL,
    [id_source]                   INT            NULL,
    [id_change_set]               INT            NULL,
    [is_multiselect]              BIT            CONSTRAINT [DF_k_referential_form_field_is_multiselect] DEFAULT ((0)) NOT NULL,
    [include_select_all_option]   BIT            CONSTRAINT [DF_k_referential_form_field_include_select_all_option] DEFAULT ((0)) NOT NULL,
    [foreign_key_field_parent_id] INT            NULL,
    CONSTRAINT [PK_k_referential_form_field] PRIMARY KEY CLUSTERED ([field_id] ASC),
    CONSTRAINT [CK_k_referential_form_field_include_select_all_option] CHECK ([is_multiselect]=(1) AND [include_select_all_option]=(1) OR [is_multiselect]=(0) AND [include_select_all_option]=(0)),
    CONSTRAINT [FK_k_referential_form_field_k_referential_form] FOREIGN KEY ([form_id]) REFERENCES [dbo].[k_referential_form] ([form_id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views] FOREIGN KEY ([foreign_table_id]) REFERENCES [dbo].[k_referential_tables_views] ([id_table_view]),
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields] FOREIGN KEY ([table_view_field_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]) ON DELETE CASCADE,
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields1] FOREIGN KEY ([foreign_key_field_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields2] FOREIGN KEY ([foreign_text_field_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields3] FOREIGN KEY ([foreign_order_field_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields4] FOREIGN KEY ([parent_key_field_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_form_field_k_referential_tables_views_fields5] FOREIGN KEY ([foreign_key_field_parent_id]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_form_field_k_unit] FOREIGN KEY ([unit_id]) REFERENCES [dbo].[k_unit] ([unit_id])
);

