CREATE TABLE [dbo].[k_reports_control] (
    [id_report_control]           INT            IDENTITY (1, 1) NOT NULL,
    [control_name]                NVARCHAR (100) NOT NULL,
    [control_type]                INT            NOT NULL,
    [layout_label]                NVARCHAR (50)  NULL,
    [layout_width]                INT            NULL,
    [layout_height]               INT            NULL,
    [source_type]                 NVARCHAR (50)  NULL,
    [source_name]                 NVARCHAR (50)  NULL,
    [source_display_field]        NVARCHAR (100) NULL,
    [source_value_field]          NVARCHAR (100) NULL,
    [source_parent_display_field] NVARCHAR (50)  NULL,
    [source_multi_select_used]    BIT            NULL,
    [source_filter_used]          BIT            NULL,
    [source_filter_field]         NVARCHAR (50)  NULL,
    [source_filter_type]          NVARCHAR (50)  NULL,
    [source_filter_value]         NVARCHAR (50)  NULL,
    [date_creation]               DATETIME       NULL,
    [date_modification]           DATETIME       NULL,
    [culture]                     BIT            NULL,
    [source_root_included]        INT            NULL,
    [auto_select]                 BIT            NULL,
    [is_default_value]            BIT            NULL,
    [default_value_type]          NVARCHAR (50)  NULL,
    [default_elementId]           NVARCHAR (100) NULL,
    [default_SP_name]             NVARCHAR (100) NULL,
    [default_column_name]         NVARCHAR (100) NULL,
    [id_source_tenant]            INT            NULL,
    [id_source]                   INT            NULL,
    [id_change_set]               INT            NULL,
    [page_size]                   INT            NULL,
    [allow_empty]                 BIT            CONSTRAINT [DF_k_reports_control_allow_empty] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_k_reports_control] PRIMARY KEY CLUSTERED ([id_report_control] ASC),
    CONSTRAINT [FK_k_reports_control_k_reports_control_type] FOREIGN KEY ([control_type]) REFERENCES [dbo].[k_reports_control_type] ([id_type])
);

