CREATE TABLE [dbo].[k_referential_grids] (
    [id_grid]                        INT            IDENTITY (1, 1) NOT NULL,
    [id_table_view]                  INT            NOT NULL,
    [id_grid_parent]                 INT            NULL,
    [name_grid]                      NVARCHAR (255) NOT NULL,
    [type_grid]                      INT            NOT NULL,
    [comments]                       NVARCHAR (MAX) NULL,
    [page_size]                      INT            NOT NULL,
    [is_addable]                     BIT            CONSTRAINT [DF_k_referential_grids_is_addable] DEFAULT ((0)) NOT NULL,
    [form_id]                        INT            NULL,
    [url]                            NVARCHAR (255) NULL,
    [is_deletable]                   BIT            CONSTRAINT [DF_k_referential_grids_is_deletable] DEFAULT ((0)) NOT NULL,
    [is_searchable]                  BIT            CONSTRAINT [DF_k_referential_grids_is_searchable] DEFAULT ((0)) NOT NULL,
    [is_exportable]                  BIT            CONSTRAINT [DF_k_referential_grids_is_exportable] DEFAULT ((0)) NOT NULL,
    [date_grid]                      SMALLDATETIME  CONSTRAINT [DF_k_referential_grids_date_grid] DEFAULT (getdate()) NULL,
    [grouping_field]                 INT            NULL,
    [frozen_column]                  INT            NULL,
    [active_trace]                   BIT            NULL,
    [filtering_field]                INT            NULL,
    [is_simulated]                   BIT            NULL,
    [is_importable]                  BIT            NULL,
    [idOwner]                        INT            NULL,
    [is_auto_resize]                 BIT            NULL,
    [is_track_change]                BIT            NULL,
    [sort_grid]                      INT            NULL,
    [width]                          INT            NULL,
    [fit_to_screen]                  BIT            CONSTRAINT [DF_k_referential_grids_fit_to_screen] DEFAULT ((1)) NOT NULL,
    [id_source_tenant]               INT            NULL,
    [id_source]                      INT            NULL,
    [id_change_set]                  INT            NULL,
    [sp_grid_add_pre]                NVARCHAR (255) NULL,
    [sp_grid_add_post]               NVARCHAR (255) NULL,
    [sp_grid_save_pre]               NVARCHAR (255) NULL,
    [sp_grid_save_post]              NVARCHAR (255) NULL,
    [sp_grid_delete_pre]             NVARCHAR (255) NULL,
    [sp_grid_delete_post]            NVARCHAR (255) NULL,
    [is_bulk_insert]                 BIT            CONSTRAINT [DF_k_referential_grids_is_bulk_insert] DEFAULT ((0)) NOT NULL,
    [is_tree]                        BIT            CONSTRAINT [DF_k_referential_grids_is_tree] DEFAULT ((0)) NOT NULL,
    [master_id_table_view_field]     INT            NULL,
    [child_id_table_view_field]      INT            NULL,
    [parent_id_table_view_field]     INT            NULL,
    [is_staging_area_enabled]        BIT            CONSTRAINT [DF_k_referential_grids_is_staging_area_enabled] DEFAULT ((0)) NOT NULL,
    [is_export_template_enabled]     BIT            CONSTRAINT [DF_k_referential_grids_is_export_template_enabled] DEFAULT ((0)) NOT NULL,
    [show_default_security_view]     BIT            CONSTRAINT [DF_k_referential_grids_show_default_security_view] DEFAULT ((1)) NOT NULL,
    [use_attached_objects]           BIT            CONSTRAINT [DF_k_referential_grids_use_attached_objects] DEFAULT ((0)) NOT NULL,
    [tree_collapse_after_save]       BIT            NULL,
    [is_password_protection_enabled] BIT            CONSTRAINT [DF_k_referential_grids_is_password_protection_enabled] DEFAULT ((0)) NOT NULL,
    [apply_user_filter]              BIT            CONSTRAINT [DF_k_referential_grids_apply_user_filter] DEFAULT ((1)) NOT NULL,
    [wrap_header]                    BIT            CONSTRAINT [DF_k_referential_grids_wrap_header] DEFAULT ((0)) NOT NULL,
    [header_tooltip]                 BIT            CONSTRAINT [DF_k_referential_grids_header_tooltip] DEFAULT ((0)) NOT NULL,
    [sp_grid_import_pre]             NVARCHAR (255) NULL,
    [sp_grid_import_post]            NVARCHAR (255) NULL,
    [allow_attached_file]            BIT            CONSTRAINT [DF_k_referential_grids_allow_attached_file] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_k_referential_grids_1] PRIMARY KEY CLUSTERED ([id_grid] ASC),
    CONSTRAINT [FK_k_referential_grids_k_referential_grid_folders] FOREIGN KEY ([id_grid_parent]) REFERENCES [dbo].[k_referential_grid_folders] ([id_folder]),
    CONSTRAINT [FK_k_referential_grids_k_referential_tables_views] FOREIGN KEY ([id_table_view]) REFERENCES [dbo].[k_referential_tables_views] ([id_table_view]),
    CONSTRAINT [FK_k_referential_grids_k_referential_tables_views_fields_child] FOREIGN KEY ([child_id_table_view_field]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_grids_k_referential_tables_views_fields_master] FOREIGN KEY ([master_id_table_view_field]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]),
    CONSTRAINT [FK_k_referential_grids_k_referential_tables_views_fields_parent] FOREIGN KEY ([parent_id_table_view_field]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field])
);


GO
CREATE NONCLUSTERED INDEX [IX__k_referential_grids__id_grid_parent]
    ON [dbo].[k_referential_grids]([id_grid_parent] ASC);

