CREATE TABLE [dbo].[k_referential_grids_fields] (
    [id_column]                       INT            IDENTITY (1, 1) NOT NULL,
    [id_grid]                         INT            NOT NULL,
    [id_field]                        INT            NOT NULL,
    [name_column]                     NVARCHAR (255) NOT NULL,
    [order_column]                    INT            NOT NULL,
    [is_editable]                     BIT            CONSTRAINT [DF_k_referential_tables_grids_is_editable] DEFAULT ((0)) NOT NULL,
    [regular_expression]              NVARCHAR (255) CONSTRAINT [DF_k_referential_tables_grids_regular_expression] DEFAULT ((0)) NULL,
    [is_sortable]                     BIT            CONSTRAINT [DF_k_referential_grids_fields_is_sortable] DEFAULT ((0)) NOT NULL,
    [error_message]                   NVARCHAR (255) NULL,
    [url]                             NVARCHAR (255) NULL,
    [width]                           INT            NULL,
    [combo_datasource_name]           NVARCHAR (255) NULL,
    [combo_datavaluefield_name]       NVARCHAR (255) NULL,
    [combo_datatextfield_name]        NVARCHAR (255) NULL,
    [combo_defaultfield_value]        NVARCHAR (50)  NULL,
    [combo_page_size]                 INT            NULL,
    [combo_filtered_column_name]      NVARCHAR (255) NULL,
    [combo_filtered_pattern]          NVARCHAR (255) NULL,
    [combo_allow_custom_text]         BIT            NULL,
    [group_index]                     INT            NULL,
    [is_frozen]                       BIT            NULL,
    [thousand_separator]              BIT            NULL,
    [decimal_precision]               INT            NULL,
    [filter_field]                    NVARCHAR (100) NULL,
    [sort_order]                      INT            NULL,
    [column_align]                    NVARCHAR (6)   NULL,
    [is_flex_used]                    BIT            DEFAULT ((0)) NOT NULL,
    [flex]                            INT            NULL,
    [id_source_tenant]                INT            NULL,
    [id_source]                       INT            NULL,
    [id_change_set]                   INT            NULL,
    [is_mandatory]                    BIT            NULL,
    [defaultfield_value]              NVARCHAR (MAX) NULL,
    [sort_direction]                  INT            NULL,
    [is_percentage_used]              BIT            CONSTRAINT [DF_k_referential_grids_fields_is_percentage_used] DEFAULT ((0)) NOT NULL,
    [combo_type]                      INT            NULL,
    [combo_dataparentvaluefield_name] NVARCHAR (MAX) NULL,
    [is_bulk_apply_used]              BIT            CONSTRAINT [DF_k_referential_grids_fields_is_bulk_apply_used] DEFAULT ((0)) NOT NULL,
    [enable_row_validation]           BIT            DEFAULT ((0)) NOT NULL,
    [is_uid_reference]                BIT            CONSTRAINT [DF_k_referential_grids_fields_is_uid_reference] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_k_referential_grids_fields] PRIMARY KEY CLUSTERED ([id_column] ASC),
    CONSTRAINT [FK_k_referential_grids_fields_k_referential_grid_field_combotype] FOREIGN KEY ([combo_type]) REFERENCES [dbo].[k_referential_grid_field_combotype] ([id_grid_field_combotype]),
    CONSTRAINT [FK_k_referential_grids_fields_k_referential_grids] FOREIGN KEY ([id_grid]) REFERENCES [dbo].[k_referential_grids] ([id_grid]),
    CONSTRAINT [FK_k_referential_grids_fields_k_referential_tables_views_fields] FOREIGN KEY ([id_field]) REFERENCES [dbo].[k_referential_tables_views_fields] ([id_field]) ON DELETE CASCADE
);

