CREATE TABLE [dbo].[nc_Document] (
    [id]                       INT            IDENTITY (1, 1) NOT NULL,
    [beginDate]                DATETIME       NULL,
    [endDate]                  DATETIME       NULL,
    [title]                    NVARCHAR (100) NULL,
    [definition]               NVARCHAR (MAX) NULL,
    [receiver]                 NVARCHAR (MAX) NULL,
    [isMailActivated]          BIT            NULL,
    [isImmediate]              BIT            NULL,
    [isPersonal]               BIT            NOT NULL,
    [idDocumentType]           INT            NOT NULL,
    [idOwner]                  INT            NULL,
    [idFolder]                 INT            NULL,
    [id_file_source]           INT            NULL,
    [acceptAllowed]            BIT            NULL,
    [rejectAllowed]            BIT            NULL,
    [isFavorite]               BIT            NULL,
    [createDate]               SMALLDATETIME  NULL,
    [is_auto_generated]        BIT            NULL,
    [file_location]            NVARCHAR (20)  NULL,
    [template_path]            NVARCHAR (100) NULL,
    [template_file_name]       NVARCHAR (100) NULL,
    [extension]                NVARCHAR (10)  NULL,
    [id_execution]             INT            NULL,
    [date_execution]           DATETIME       NULL,
    [subscription_query_count] INT            NULL,
    [id_subscription]          INT            NULL,
    [definition_original]      NVARCHAR (MAX) NULL,
    [docusign_template_id]     NVARCHAR (100) NULL,
    [use_translate]            BIT            CONSTRAINT [DF_nc_Document_use_translate] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_nc_DocumentNotification] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_nc_Document_k_users] FOREIGN KEY ([idOwner]) REFERENCES [dbo].[k_users] ([id_user]),
    CONSTRAINT [FK_nc_Document_nc_Folder] FOREIGN KEY ([idFolder]) REFERENCES [dbo].[nc_Folder] ([id_folder]),
    CONSTRAINT [FK_nc_Document_rps_file_source] FOREIGN KEY ([id_file_source]) REFERENCES [dbo].[rps_file_source] ([id_file_source]),
    CONSTRAINT [FK_nc_DocumentNotification_nc_DocumentType] FOREIGN KEY ([idDocumentType]) REFERENCES [dbo].[nc_DocumentType] ([id])
);

