CREATE TABLE [dbo].[py_PayeeHisto] (
    [id_histo]              INT             IDENTITY (1, 1) NOT NULL,
    [start_date_histo]      DATETIME        NOT NULL,
    [end_date_histo]        DATETIME        NOT NULL,
    [idPayee]               INT             NULL,
    [codePayee]             NVARCHAR (50)   NOT NULL,
    [id_sup]                INT             NULL,
    [firstname]             NVARCHAR (100)  NULL,
    [lastname]              NVARCHAR (255)  NULL,
    [email]                 NVARCHAR (255)  NULL,
    [birth_date]            DATETIME        NULL,
    [age]                   FLOAT (53)      NULL,
    [start_date_company]    DATETIME        NULL,
    [end_date_company]      DATETIME        NULL,
    [start_date_group]      DATETIME        NULL,
    [end_date_group]        DATETIME        NULL,
    [start_date_job]        DATETIME        NULL,
    [end_date_job]          DATETIME        NULL,
    [base_salary]           DECIMAL (18, 4) NULL,
    [base_salary_period]    DECIMAL (18, 4) NULL,
    [variable_period]       DECIMAL (18, 4) NULL,
    [nb_year_experience]    FLOAT (53)      NULL,
    [months_per_year]       INT             NULL,
    [hours_per_month]       FLOAT (53)      NULL,
    [weight_structure_1]    FLOAT (53)      NULL,
    [weight_structure_2]    FLOAT (53)      NULL,
    [variable]              DECIMAL (18, 4) NULL,
    [company_car]           BIT             NULL,
    [id_category]           INT             NULL,
    [id_grade]              INT             NULL,
    [id_contract]           INT             NULL,
    [id_agreement]          INT             NULL,
    [id_cost_center]        INT             NULL,
    [id_group]              INT             NULL,
    [id_gender]             INT             NULL,
    [id_activity_status]    INT             NULL,
    [id_job]                INT             NULL,
    [id_department]         INT             NULL,
    [id_organization]       INT             NULL,
    [id_structure_1]        INT             NULL,
    [id_structure_2]        INT             NULL,
    [id_geography]          INT             NULL,
    [id_territory]          INT             NULL,
    [id_variable_currency]  INT             NULL,
    [id_title]              INT             NULL,
    [id_nationality]        INT             NULL,
    [id_pool]               INT             NULL,
    [id_job_country]        INT             NULL,
    [id_benefit]            INT             NULL,
    [id_salary_currency]    INT             NULL,
    [id_version]            INT             NULL,
    [date_loading]          DATETIME        NULL,
    [id_payment_currency]   INT             NULL,
    [id_performance_rating] INT             NULL,
    [comparatio]            NUMERIC (6, 4)  NULL,
    [lump_sum]              FLOAT (53)      NULL,
    CONSTRAINT [PK_Histo_Employee] PRIMARY KEY CLUSTERED ([id_histo] ASC),
    CONSTRAINT [FK_k_collaborateurs_histo_k_collaborateurs] FOREIGN KEY ([idPayee]) REFERENCES [dbo].[py_Payee] ([idPayee]),
    CONSTRAINT [FK_k_collaborateurs_histo_k_collaborateurs_sup] FOREIGN KEY ([id_sup]) REFERENCES [dbo].[py_Payee] ([idPayee])
);


GO
CREATE NONCLUSTERED INDEX [IX_py_PayeeHisto_idPayee_start_date_histo_end_date_histo]
    ON [dbo].[py_PayeeHisto]([idPayee] ASC, [start_date_histo] ASC, [end_date_histo] ASC);

