CREATE TABLE [dbo].[py_PayeeImport] (
    [id_import]                      INT             IDENTITY (1, 1) NOT NULL,
    [codePayee]                      NVARCHAR (50)   NOT NULL,
    [code_sup]                       NVARCHAR (50)   NULL,
    [ss_nb]                          NVARCHAR (50)   NULL,
    [lastname]                       NVARCHAR (255)  NULL,
    [firstname]                      NVARCHAR (255)  NULL,
    [email]                          NVARCHAR (255)  NULL,
    [birth_date]                     SMALLDATETIME   NULL,
    [home_phone]                     NVARCHAR (50)   NULL,
    [mobile_phone]                   NVARCHAR (50)   NULL,
    [address_street]                 NVARCHAR (255)  NULL,
    [address_postal_code]            NVARCHAR (255)  NULL,
    [address_city]                   NVARCHAR (255)  NULL,
    [address_country]                NVARCHAR (255)  NULL,
    [family_situation]               NVARCHAR (255)  NULL,
    [children_nb]                    INT             NULL,
    [image]                          VARBINARY (MAX) NULL,
    [attachment]                     VARBINARY (MAX) NULL,
    [age]                            INT             NULL,
    [start_date_company]             DATETIME        NULL,
    [end_date_company]               DATETIME        NULL,
    [start_date_group]               DATETIME        NULL,
    [end_date_group]                 DATETIME        NULL,
    [start_date_job]                 DATETIME        NULL,
    [end_date_job]                   DATETIME        NULL,
    [base_salary]                    DECIMAL (18, 4) NULL,
    [base_salary_period]             INT             NULL,
    [variable_period]                INT             NULL,
    [nb_year_experience]             FLOAT (53)      NULL,
    [months_per_year]                INT             NULL,
    [hours_per_month]                FLOAT (53)      NULL,
    [weight_structure_1]             FLOAT (53)      NULL,
    [weight_structure_2]             FLOAT (53)      NULL,
    [variable]                       DECIMAL (18, 4) NULL,
    [company_car]                    BIT             NULL,
    [code_category]                  NVARCHAR (50)   NULL,
    [code_grade]                     NVARCHAR (50)   NULL,
    [code_contract]                  NVARCHAR (50)   NULL,
    [code_agreement]                 NVARCHAR (50)   NULL,
    [code_cost_center]               NVARCHAR (50)   NULL,
    [code_gender]                    NVARCHAR (50)   NULL,
    [code_activity_status]           NVARCHAR (50)   NULL,
    [code_job]                       NVARCHAR (50)   NULL,
    [code_department]                NVARCHAR (50)   NULL,
    [code_organization]              NVARCHAR (50)   NULL,
    [code_structure_1]               NVARCHAR (50)   NULL,
    [code_structure_2]               NVARCHAR (50)   NULL,
    [code_geography]                 NVARCHAR (50)   NULL,
    [code_territory]                 NVARCHAR (50)   NULL,
    [code_variable_currency]         NVARCHAR (50)   NULL,
    [code_title]                     NVARCHAR (50)   NULL,
    [code_nationality]               NVARCHAR (50)   NULL,
    [code_pool]                      NVARCHAR (50)   NULL,
    [code_job_country]               NVARCHAR (50)   NULL,
    [code_benefit]                   NVARCHAR (50)   NULL,
    [code_salary_currency]           NVARCHAR (50)   NULL,
    [code_payment_currency]          NVARCHAR (50)   NULL,
    [salary1]                        DECIMAL (18, 4) NULL,
    [salary2]                        DECIMAL (18, 4) NULL,
    [salary3]                        DECIMAL (18, 4) NULL,
    [salary4]                        DECIMAL (18, 4) NULL,
    [date_salary1]                   DATETIME        NULL,
    [date_salary2]                   DATETIME        NULL,
    [date_salary3]                   DATETIME        NULL,
    [date_salary4]                   DATETIME        NULL,
    [company_mobile]                 DECIMAL (18)    NULL,
    [company_laptop]                 BIT             NULL,
    [company_insurance]              BIT             NULL,
    [id_version]                     INT             NULL,
    [date_loading]                   DATETIME        NOT NULL,
    [start_date_histo]               DATETIME        NOT NULL,
    [data_origine]                   NVARCHAR (20)   NULL,
    [code_performance_rating]        NVARCHAR (50)   NULL,
    [login]                          NVARCHAR (50)   NULL,
    [code_jobfamily]                 NVARCHAR (50)   NULL,
    [code_host_country]              NVARCHAR (50)   NULL,
    [code_home_country]              NVARCHAR (50)   NULL,
    [code_division]                  NVARCHAR (50)   NULL,
    [code_businessunit]              NVARCHAR (50)   NULL,
    [code_band]                      NVARCHAR (50)   NULL,
    [FTE]                            DECIMAL (18, 2) NULL,
    [annual_fulltime_basesalary_usd] DECIMAL (18, 2) NULL,
    [annual_fulltime_basesalary_lc]  DECIMAL (18, 2) NULL,
    [effective_basesalary_lc]        DECIMAL (18, 2) NULL,
    [payment_periods]                DECIMAL (18, 2) NULL,
    [benefit_companycar]             DECIMAL (18, 2) NULL,
    [benefit_housingallowance]       DECIMAL (18, 2) NULL,
    [benefit_healthcare]             DECIMAL (18, 2) NULL,
    [wealth_pensionplan]             DECIMAL (18, 2) NULL,
    [code_potential_rating]          NVARCHAR (50)   NULL,
    CONSTRAINT [PK_k_collaborateurs_import] PRIMARY KEY CLUSTERED ([id_import] ASC)
);

