CREATE TABLE [dbo].[tb_CRP_Process_Template_archive] (
    [id_histo]                 INT             NOT NULL,
    [start_date_histo]         DATETIME        NOT NULL,
    [end_date_histo]           DATETIME        NOT NULL,
    [id_plan]                  INT             NULL,
    [name_plan]                NVARCHAR (255)  NOT NULL,
    [FreezeDate]               DATE            NULL,
    [idPayee]                  INT             NOT NULL,
    [codePayee]                NVARCHAR (50)   NOT NULL,
    [lastname]                 NVARCHAR (255)  NOT NULL,
    [firstname]                NVARCHAR (255)  NOT NULL,
    [fullname]                 NVARCHAR (511)  NOT NULL,
    [PersonnelNumber]          NVARCHAR (15)   NULL,
    [BirthDate]                DATETIME        NULL,
    [Age]                      INT             NULL,
    [Gender]                   NVARCHAR (5)    NULL,
    [EntryDate]                DATETIME        NULL,
    [Anniversary]              INT             NULL,
    [LeavingDate]              DATETIME        NULL,
    [EmployeeClass]            NVARCHAR (50)   NULL,
    [Org_BeginDate]            DATE            NULL,
    [Org_EndDate]              DATE            NULL,
    [Org_ReportManager]        NVARCHAR (101)  NULL,
    [Org_CostCenter_Code]      NVARCHAR (5)    NULL,
    [Org_CostCenter_Desc]      NVARCHAR (50)   NULL,
    [Org_BusinessUnit_Code]    NVARCHAR (15)   NULL,
    [Org_BusinessUnit_Desc]    NVARCHAR (50)   NULL,
    [Org_BusinessArea_Code]    NVARCHAR (10)   NULL,
    [Org_BusinessArea_Desc]    NVARCHAR (50)   NULL,
    [Org_Department_Code]      NVARCHAR (10)   NULL,
    [Org_Department_Desc]      NVARCHAR (50)   NULL,
    [Org_LegalEntity_Code]     NVARCHAR (4)    NULL,
    [Org_LegalEntity_Desc]     NVARCHAR (50)   NULL,
    [FTE_BeginDate]            DATE            NULL,
    [FTE_Enddate]              DATE            NULL,
    [FTE_Current]              DECIMAL (2, 1)  NULL,
    [FTE_Future]               DECIMAL (2, 1)  NULL,
    [Job_BeginDate]            DATE            NULL,
    [Job_EndDate]              DATE            NULL,
    [JobCode_Current]          NVARCHAR (50)   NULL,
    [CurrentTitleCode]         NVARCHAR (6)    NULL,
    [CurrentTitle]             NVARCHAR (50)   NULL,
    [has_allowances]           NVARCHAR (50)   NULL,
    [Base_Salary_Currency]     NVARCHAR (3)    NULL,
    [Base_Salary_Current]      DECIMAL (32, 2) NULL,
    [Bonus_Year]               INT             NULL,
    [Bonus_Currency]           NVARCHAR (3)    NULL,
    [Target_Bonus_Prof_Staff]  DECIMAL (32, 2) NULL,
    [Target_Bonus_Admin_Staff] DECIMAL (32, 2) NULL,
    [Bonus_Signon]             DECIMAL (32, 2) NULL,
    [Bonus_Exit]               INT             NULL,
    [Target_HF_Point_Min]      DECIMAL (32, 2) NULL,
    [Target_HF_Point_Max]      DECIMAL (32, 2) NULL,
    [Target_PE_Point_Min]      DECIMAL (32, 2) NULL,
    [Target_PE_Point_Max]      DECIMAL (32, 2) NULL,
    [HF_Point_Value]           DECIMAL (32, 2) NULL,
    [PE_Point_Value]           DECIMAL (32, 2) NULL,
    [LTIS_Current]             DECIMAL (32, 2) NULL,
    [Target_Bonus_Year]        INT             NULL,
    [Target_Bonus_Currency]    NVARCHAR (3)    NULL
);

